# Generated by Django 5.0 on 2023-12-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plutusAI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='target',
        ),
        migrations.AddField(
            model_name='configuration',
            name='initial_sl',
            field=models.CharField(default='10', max_length=10),
        ),
        migrations.AddField(
            model_name='configuration',
            name='is_place_sl_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='safe_sl',
            field=models.CharField(default='3', max_length=10),
        ),
        migrations.AddField(
            model_name='configuration',
            name='target_for_safe_sl',
            field=models.CharField(default='10', max_length=10),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='index_name',
            field=models.CharField(default='nifty50', max_length=30),
        ),
        migrations.AddField(
            model_name='configuration',
            name='levels',
            field=models.ManyToManyField(default=None, to='plutusAI.levels'),
        ),
    ]
