# Generated by Django 5.0 on 2023-12-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plutusAI', '0002_levels_remove_configuration_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='trailing_points',
            field=models.CharField(default='10', max_length=10),
        ),
        migrations.AddField(
            model_name='configuration',
            name='trend_check_points',
            field=models.CharField(default='15', max_length=10),
        ),
    ]
