# Generated by Django 5.2.6 on 2026-05-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plutusAI", "0002_telegramsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramBotConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bot_id", models.CharField(default="", max_length=200)),
                ("admin_chat_ids", models.CharField(default="", max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name="brokerdetails",
            name="broker_forex_server",
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="brokerdetails",
            name="broker_password",
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="manualorders",
            name="index_group",
            field=models.CharField(default="indian_index", max_length=20),
        ),
        migrations.AddField(
            model_name="manualorders",
            name="on_candle_close",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="manualorders",
            name="producttype",
            field=models.CharField(
                choices=[("INTRADAY", "INTRADAY"), ("CARRYFORWARD", "CARRYFORWARD")],
                default="INTRADAY",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="manualorders",
            name="strategy_name",
            field=models.CharField(blank=True, default=None, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name="manualorders",
            name="strategy_type",
            field=models.CharField(
                blank=True, default="default", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="manualorders",
            name="timeframe",
            field=models.CharField(
                choices=[
                    ("ONE_MINUTE", "ONE_MINUTE"),
                    ("THREE_MINUTE", "THREE_MINUTE"),
                    ("FIVE_MINUTE", "FIVE_MINUTE"),
                    ("TEN_MINUTE", "TEN_MINUTE"),
                    ("FIFTEEN_MINUTE", "FIFTEEN_MINUTE"),
                    ("THIRTY_MINUTE", "THIRTY_MINUTE"),
                    ("ONE_HOUR", "ONE_HOUR"),
                    ("ONE_DAY", "ONE_DAY"),
                ],
                default="FIVE_MINUTE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="orderbook",
            name="index_group",
            field=models.CharField(default="indian_index", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="orderbook",
            name="order_id",
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="orderbook",
            name="position_id",
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="telegramsettings",
            name="bot_id",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="userauthtokens",
            name="index_group",
            field=models.CharField(default="indian_index", max_length=20),
        ),
        migrations.AlterField(
            model_name="brokerdetails",
            name="broker_api_token",
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="brokerdetails",
            name="broker_mpin",
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="brokerdetails",
            name="broker_name",
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="brokerdetails",
            name="broker_qr",
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="brokerdetails",
            name="broker_user_id",
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="brokerdetails",
            name="broker_user_name",
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="brokerdetails",
            name="index_group",
            field=models.CharField(default="indian_index", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="brokerdetails",
            name="is_demo_trading_enabled",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="brokerdetails",
            name="token_status",
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="brokerdetails",
            name="user_id",
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="indexdetails",
            name="index_group",
            field=models.CharField(default="indian_index", max_length=20),
        ),
        migrations.AlterField(
            model_name="manualorders",
            name="current_premium",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="manualorders",
            name="order_id",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="manualorders",
            name="order_status",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="manualorders",
            name="stop_loss",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="manualorders",
            name="target",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="manualorders",
            name="time",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="manualorders",
            name="trigger",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="manualorders",
            name="unique_order_id",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
