# Generated by Django 5.0 on 2023-12-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plutusAI', '0003_configuration_trailing_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='levels',
        ),
        migrations.AddField(
            model_name='configuration',
            name='levels',
            field=models.CharField(default=None, max_length=5000),
        ),
    ]
