# Generated by Django 5.0 on 2023-12-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plutusAI', '0004_remove_configuration_levels_configuration_levels'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Levels',
        ),
        migrations.AddField(
            model_name='configuration',
            name='user_id',
            field=models.CharField(default='10', max_length=500),
        ),
    ]
