# Generated by Django 5.0 on 2023-12-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plutusAI', '0006_configuration_start_scheduler'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='stage',
            field=models.CharField(default='stopped', max_length=250),
        ),
        migrations.AddField(
            model_name='configuration',
            name='strike',
            field=models.CharField(default='10', max_length=5),
        ),
    ]
