# Generated by Django 5.0 on 2023-12-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plutusAI', '0007_configuration_stage_configuration_strike'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='10', max_length=500)),
                ('broker_user_id', models.CharField(default=None, max_length=250)),
                ('broker_user_name', models.CharField(default=None, max_length=250)),
                ('broker_name', models.CharField(default=None, max_length=250)),
                ('token_status', models.CharField(default=None, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='10', max_length=500)),
                ('time', models.CharField(default=None, max_length=250)),
                ('script_name', models.CharField(default=None, max_length=250)),
                ('qty', models.CharField(default=None, max_length=250)),
                ('entry_price', models.CharField(default=None, max_length=250)),
                ('exit_price', models.CharField(default=None, max_length=250)),
                ('status', models.CharField(default=None, max_length=250)),
            ],
        ),
    ]
