# Generated by Django 5.0 on 2023-12-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plutusAI', '0009_brokerdetails_is_demo_trading_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokerdetails',
            name='user_id',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='user_id',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='orderbook',
            name='user_id',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
