# Generated by Django 5.0 on 2024-01-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plutusAI', '0010_alter_brokerdetails_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerdetails',
            name='broker_api_token',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='brokerdetails',
            name='broker_mpin',
            field=models.CharField(blank=True, default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='brokerdetails',
            name='broker_qr',
            field=models.CharField(blank=True, default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='brokerdetails',
            name='broker_user_name',
            field=models.CharField(blank=True, default=None, max_length=250),
        ),
    ]
