# Generated by Django 5.0 on 2024-01-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plutusAI', '0011_brokerdetails_broker_api_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_name', models.CharField(default=None, max_length=50)),
                ('index_group', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default=None, max_length=500)),
                ('index_name', models.CharField(default=None, max_length=50)),
                ('job_id', models.CharField(default=None, max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='configuration',
            name='index_name',
            field=models.CharField(default='nifty50', max_length=50),
        ),
    ]
