# Generated by Django 5.0 on 2024-01-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plutusAI', '0012_indexdetails_jobdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerdetails',
            name='index_group',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
