# Generated by Django 5.0 on 2024-01-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plutusAI', '0013_brokerdetails_index_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default=None, max_length=500)),
                ('registed_date', models.CharField(default=None, max_length=200)),
                ('renew_date', models.CharField(default=None, max_length=200)),
                ('opted_index', models.CharField(default=None, max_length=500)),
            ],
        ),
    ]
