# Generated by Django 5.0 on 2024-01-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plutusAI', '0014_paymentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='terminate_job',
            field=models.BooleanField(default=True),
        ),
    ]
