# Generated by Django 5.0 on 2024-01-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plutusAI', '0015_jobdetails_terminate_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='terminate_job',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
