# Generated by Django 5.0 on 2024-01-15 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plutusAI', '0016_alter_jobdetails_terminate_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdetails',
            name='terminate_job',
        ),
    ]
