# Generated by Django 5.0 on 2024-01-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plutusAI', '0019_rename_index_ltp_indexdetails_ltp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='lots',
            field=models.CharField(default='stopped', max_length=50),
        ),
    ]
