# Generated by Django 5.0 on 2024-01-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plutusAI', '0021_indexdetails_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='lots',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
