# Generated by Django 5.0 on 2024-01-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plutusAI', '0022_alter_configuration_lots'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexdetails',
            name='current_expiry',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='indexdetails',
            name='next_expiry',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
