# Generated by Django 5.0 on 2024-01-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plutusAI', '0023_indexdetails_current_expiry_indexdetails_next_expiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderbook',
            old_name='time',
            new_name='entry_time',
        ),
        migrations.AddField(
            model_name='orderbook',
            name='exit_time',
            field=models.CharField(blank=True, default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='orderbook',
            name='entry_price',
            field=models.CharField(blank=True, default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='orderbook',
            name='exit_price',
            field=models.CharField(blank=True, default=None, max_length=250),
        ),
    ]
