# Generated by Django 5.0 on 2024-02-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plutusAI', '0024_rename_time_orderbook_entry_time_orderbook_exit_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportedBrokers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_name', models.CharField(default=None, max_length=200)),
                ('instruments', models.TextField(blank=True)),
            ],
        ),
    ]
