# Generated by Django 5.0 on 2024-02-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plutusAI', '0027_alter_supportedbrokers_instruments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportedbrokers',
            name='instruments',
            field=models.TextField(blank=True, default=None),
        ),
    ]
