# Generated by Django 5.0 on 2024-02-04 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plutusAI', '0028_alter_supportedbrokers_instruments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupportedBrokers',
        ),
    ]
