# Generated by Django 5.0 on 2024-02-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plutusAI', '0029_delete_supportedbrokers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbook',
            name='exit_price',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='orderbook',
            name='exit_time',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
