# Generated by Django 5.0.2 on 2024-02-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plutusAI', '0030_alter_orderbook_exit_price_alter_orderbook_exit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbook',
            name='cumulative_p_l',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
