# Generated by Django 5.0.2 on 2024-02-17 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plutusAI', '0031_orderbook_cumulative_p_l'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderbook',
            old_name='cumulative_p_l',
            new_name='total',
        ),
    ]
