# Generated by Django 5.0.2 on 2024-02-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plutusAI', '0032_rename_cumulative_p_l_orderbook_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbook',
            name='entry_time',
            field=models.DateTimeField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='orderbook',
            name='exit_time',
            field=models.DateTimeField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
