# Generated by Django 5.0.2 on 2024-02-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plutusAI', '0033_alter_orderbook_entry_time_alter_orderbook_exit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbook',
            name='entry_time',
            field=models.DateTimeField(),
        ),
    ]
