# Generated by Django 5.0.2 on 2024-02-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plutusAI', '0034_alter_orderbook_entry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbook',
            name='entry_time',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderbook',
            name='exit_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
